// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/figment-networks/indexing-engine/pipeline (interfaces: PayloadFactory,Payload,Source,Sink,Stage,StageRunner,Task)

// Package mock_pipeline is a generated GoMock package.
package mock_pipeline

import (
	context "context"
	pipeline "github.com/figment-networks/indexing-engine/pipeline"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPayloadFactory is a mock of PayloadFactory interface
type MockPayloadFactory struct {
	ctrl     *gomock.Controller
	recorder *MockPayloadFactoryMockRecorder
}

// MockPayloadFactoryMockRecorder is the mock recorder for MockPayloadFactory
type MockPayloadFactoryMockRecorder struct {
	mock *MockPayloadFactory
}

// NewMockPayloadFactory creates a new mock instance
func NewMockPayloadFactory(ctrl *gomock.Controller) *MockPayloadFactory {
	mock := &MockPayloadFactory{ctrl: ctrl}
	mock.recorder = &MockPayloadFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPayloadFactory) EXPECT() *MockPayloadFactoryMockRecorder {
	return m.recorder
}

// GetPayload mocks base method
func (m *MockPayloadFactory) GetPayload() pipeline.Payload {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload")
	ret0, _ := ret[0].(pipeline.Payload)
	return ret0
}

// GetPayload indicates an expected call of GetPayload
func (mr *MockPayloadFactoryMockRecorder) GetPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockPayloadFactory)(nil).GetPayload))
}

// MockPayload is a mock of Payload interface
type MockPayload struct {
	ctrl     *gomock.Controller
	recorder *MockPayloadMockRecorder
}

// MockPayloadMockRecorder is the mock recorder for MockPayload
type MockPayloadMockRecorder struct {
	mock *MockPayload
}

// NewMockPayload creates a new mock instance
func NewMockPayload(ctrl *gomock.Controller) *MockPayload {
	mock := &MockPayload{ctrl: ctrl}
	mock.recorder = &MockPayloadMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPayload) EXPECT() *MockPayloadMockRecorder {
	return m.recorder
}

// MarkAsProcessed mocks base method
func (m *MockPayload) MarkAsProcessed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkAsProcessed")
}

// MarkAsProcessed indicates an expected call of MarkAsProcessed
func (mr *MockPayloadMockRecorder) MarkAsProcessed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsProcessed", reflect.TypeOf((*MockPayload)(nil).MarkAsProcessed))
}

// SetCurrentHeight mocks base method
func (m *MockPayload) SetCurrentHeight(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCurrentHeight", arg0)
}

// SetCurrentHeight indicates an expected call of SetCurrentHeight
func (mr *MockPayloadMockRecorder) SetCurrentHeight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentHeight", reflect.TypeOf((*MockPayload)(nil).SetCurrentHeight), arg0)
}

// MockSource is a mock of Source interface
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
}

// MockSourceMockRecorder is the mock recorder for MockSource
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Current mocks base method
func (m *MockSource) Current() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Current indicates an expected call of Current
func (mr *MockSourceMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockSource)(nil).Current))
}

// Err mocks base method
func (m *MockSource) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err
func (mr *MockSourceMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockSource)(nil).Err))
}

// Next mocks base method
func (m *MockSource) Next(arg0 context.Context, arg1 pipeline.Payload) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next
func (mr *MockSourceMockRecorder) Next(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockSource)(nil).Next), arg0, arg1)
}

// MockSink is a mock of Sink interface
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
}

// MockSinkMockRecorder is the mock recorder for MockSink
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Consume mocks base method
func (m *MockSink) Consume(arg0 context.Context, arg1 pipeline.Payload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume
func (mr *MockSinkMockRecorder) Consume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockSink)(nil).Consume), arg0, arg1)
}

// MockStage is a mock of Stage interface
type MockStage struct {
	ctrl     *gomock.Controller
	recorder *MockStageMockRecorder
}

// MockStageMockRecorder is the mock recorder for MockStage
type MockStageMockRecorder struct {
	mock *MockStage
}

// NewMockStage creates a new mock instance
func NewMockStage(ctrl *gomock.Controller) *MockStage {
	mock := &MockStage{ctrl: ctrl}
	mock.recorder = &MockStageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStage) EXPECT() *MockStageMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockStage) Run(arg0 context.Context, arg1 pipeline.Payload, arg2 *pipeline.Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockStageMockRecorder) Run(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStage)(nil).Run), arg0, arg1, arg2)
}

// MockStageRunner is a mock of StageRunner interface
type MockStageRunner struct {
	ctrl     *gomock.Controller
	recorder *MockStageRunnerMockRecorder
}

// MockStageRunnerMockRecorder is the mock recorder for MockStageRunner
type MockStageRunnerMockRecorder struct {
	mock *MockStageRunner
}

// NewMockStageRunner creates a new mock instance
func NewMockStageRunner(ctrl *gomock.Controller) *MockStageRunner {
	mock := &MockStageRunner{ctrl: ctrl}
	mock.recorder = &MockStageRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStageRunner) EXPECT() *MockStageRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockStageRunner) Run(arg0 context.Context, arg1 pipeline.Payload, arg2 pipeline.TaskValidator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockStageRunnerMockRecorder) Run(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStageRunner)(nil).Run), arg0, arg1, arg2)
}

// MockTask is a mock of Task interface
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
}

// MockTaskMockRecorder is the mock recorder for MockTask
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockTask) Run(arg0 context.Context, arg1 pipeline.Payload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockTaskMockRecorder) Run(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTask)(nil).Run), arg0, arg1)
}
