name: Indexing engine
# This workflow is triggered on pushes to the repository only when pushing new tag.
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: CI for indexing-engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Run tests
        run: make test
